apiRules:
- exclude:
    uidRegex: ^Realms\.RealmObject\.Get.*Value.*$
    type: Method
- exclude:
    uidRegex: ^Realms\.RealmObject\.Set.*Value.*$
    type: Method
- exclude:
    uidRegex: ^Realms\.RealmObject\.GetBacklinks.*$
    type: Method
- exclude:
    uidRegex: ^Realms\.Weaving$
    type: Namespace
- exclude:
    uidRegex: ^Realms\.PreserveAttribute$
    type: Type
- exclude:
    uidRegex: ^Realms\.WovenAttribute$
    type: Type
- exclude:
    uidRegex: ^Realms\.WovenPropertyAttribute$
    type: Type
- exclude:
    uidRegex: ^Realms\.Dynamic$
    type: Namespace
- exclude:
    uidRegex: ^Realms\.RealmCollectionBase`1.*$
    type: Type
- exclude:
    uidRegex: ^Realms\.RealmList`1$
    type: Type
- include:
    hasAttribute:
      uid: System.ComponentModel.EditorBrowsableAttribute
      ctorArguments:
      - System.ComponentModel.EditorBrowsableState.Never
